extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:jsx-a11y/recommended
  - prettier
  - prettier/react
plugins:
  - flowtype
  - react
  - import
  - jsx-a11y
parser: babel-eslint
rules:
  react/props-types: 0
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  browser: true
  node: true
  jest: true
